optimizely/marketing-website

grunt/config.js

@kylerush @stewsmith This PR reverts https://github.com/optimizely/marketing-website/pull/771 that was in response to https://github.com/optimizely/marketing-website/pull/770 which resulted in an outage to the marketing website.  
PR can be tested by running grunt build and in `dist/assets/css/` comparing the stylesheet hash to that in any index.html in `dist`

revert aseetsDir path for file reving in grunt/config

---

website/partners/technology/segment/index.hbs

The segment logo on the /partners/technology page is currently broken. This PR fixes that.

Change image src for segment

---

website-guts/templates/layouts/wrapper.hbs
website/android/index.hbs
website/mobile/index.hbs
website/pricing/index.hbs
website/statistics/index.hbs

[MKT-953](https://optimizely.atlassian.net/browse/MKT-953)
* Add link to /statistics page to the Products dropdown menu as: "Stats Engine"
* Add link to /statistics to the site footer, under Product features and benefits menu as: "Stats Engine"
* Update meta info on page:
- seo_title: "Optimizely Stats Engine" 
- og_title: "Optimizely Stats Engine" 
- og_description: "Statistics for the Internet age is here."

MKT-953 -- Add stats engine to navs, update stats metadata

---

grunt/concat.js
website-guts/assets/css/pages/events.scss
website-guts/assets/js/pages/events.js
website-guts/assets/js/utils/stringify_error.js
website/events/index.hbs

This PR address https://optimizely.atlassian.net/browse/MKT-886 for the broken API request to Google Calendar api for /events.  Google released a v3 api and apparently deprecated the old one. The new API requires:
- a script tag to load the gapi api on the page
- turning on the google calendar integration in the developers console
- generating an public browser API key for the Calendar integration
- enabling domains for this integration
In addition to old functionality I could no longer restrict request to pull past and future data separately. I had to pull all the data and sort it appropriately.  The request is made through the gapi API which returns an object rather than JSON.  Therefore, error reporting logic for JSON parsing of request was no longer necessary.
Additional functionality …

broken request for Google Calendar endpoint on events page

---

website-guts/assets/js/pages/free-trial.js

Last Friday David and I deployed some code that reports all JavaScript errors on the marketing website to Google Analytics. This uncovered a JavaScript bug on the PPC landing page, specifically with the content symmetry script. The content symmetry script adjusts the text on the PPC landing page based on the message in the ad. I believe this bug has been in production since the launch of the new marketing website. This PR fixes this bug.

Add strict type checking to free trial js.

---

website-guts/templates/client/loggedInUtilityNav.hbs

This PR addresses JIRA https://optimizely.atlassian.net/browse/MKT-835 to remove the hardcode links for dashboard and account in the logged in utility nav.  This is relatively inconsequential now as logged in users cannot redirect back to the marketing site out of the product

Make relative paths for dashboard and account in signed in utility nav

---

website-guts/templates/layouts/wrapper.hbs
website/contact/index.hbs
website/terms/05/30/2013/index.hbs

@dtothefp this should avoid issues like the social icons in the footer getting messed up... If we ever need these swaps we can always put them back.

Remove unnecessary content swap classes to avoid bugs

---

website-guts/assets/js/utils/oform_globals.js

From my phone conversation we determined that:
- we could not figure out to change API name within marketo interface for custom fields
- we are unsure if changing field name in SalesForce resulted in changing the Munchkin API name for the custom field
- we created 2 new custom fields to test the IOS checkbox
- 1 with default created name by Marketo, this seems to have no underscores and lowercase first letter
- 2 we altered the default name and Capitalized the first letter.

Add testing fields for IOS Marketo population test

---

grunt/assemble.js
package.json
website-guts/templates/layouts/wrapper.hbs

Addresses https://optimizely.atlassian.net/browse/MKT-1006 to dynamically update to the current year for copyright in the footer.
*Note: that upgrading to Assemble v6 we will have to upgrade this helpers https://github.com/helpers/helper-moment/issues/1*

add moment helper to fix copyright year in footer

---

website-guts/assets/js/layouts/trial-form.js
website-guts/assets/js/pages/mobile.js

This PR is a preparation for an experiment that we are going to run on the mobile product page for ads audience. We are adding more reporting.
Reporting changes to the /mobile page:
1. Added blur reporting
2. Added focus reporting
Reporting changes to the /free-trial page:
1. Changed "blur" to "focus to match the real event happening
2. Added blur reporting
Note that for the /mobile page, since there are two forms, I'm sending out two events, one specific to the form on which it occurred and another that is not specific the form on which it occurred. The latter event helps us understand aggregate behavior and is particularly necessary for the upcoming experiment.

Add more tracking events for an experiment.

---

website-guts/assets/js/pages/mobile.js

This gives us the ability to group error on both the top and bottom forms. Without this we couldn't track overall error rate in Optimizely during our next experiment. In the past, on validation error, only this was sent: `mobile-signup-form-top password1 error submit`. With this PR, in addition to that event, it will also send `mobile-signup-form password1 error submit`.
It also ads a submit tracking event in the before function. This will help us measure the `submit : success` ratio.

Enhance error tracking for mobile experiment.

---

grunt/modernizr.js
website-guts/assets/css/pages/homepage.scss
website/index.hbs

This PR adds a small delay and fade-in for the CTA on the homepage. This is so that we can pull the Demandbase information and update the CTA language before the content fades in. It helps us avoid the so-called flash of unstyled content.

Fade-in for CTA on homepage.

---

website-guts/assets/js/om/layouts/original.js

Three changes:
1. Doesn't show validation error on blur if the field has no value (this is how the old page does it). To test focus into both the email and URL fields, don't enter a value, then focus out, you should not see any red/validation error. Then enter an invalid value in URL and email fields (like "t"), focus out, then see the validation errors. 
2. Adds a `seo-form success after error true` or `seo-form success after error false` to track if the person that submitted the form successfully encountered a validation error. This can only be tested in production.
3. Fixes/adds focus and blur reporting. You can see in the diff that the existing focus reporting was fucked up because it was set to track blur, but was reporting focus.
4. Adds `change engagement` events to track when the …

Modify OM reporting

---

website-guts/templates/partials/feature_list.hbs
website/features-and-plans/index.hbs
website/pricing/index.hbs

This PR addresses https://optimizely.atlassian.net/browse/MKT-1284 for swapping mobile related content on the pricing page for Japan.  
- added SL_swap on `/pricing` and `/features-and-plans` for "powerful" container content `id="powerful-pricing-text"`
- added SL_hide for `asterick` class `<p>` tag containing text about android
- added SL_swap for multichannel experience text `id="multichannel-text"`
- added SL_swap for multichannel experience text container in order to change the checkbox `id="multichannel-cont"`

add swap and hide tags for japan pricing swap

---

website-guts/assets/js/components/modal-signup.js
website-guts/assets/js/components/modals.js
website-guts/assets/js/pages/feature-list.js
website-guts/assets/js/pages/features-and-plans.js
website-guts/assets/js/pages/homepage.js
website-guts/assets/js/pages/pricing.js
website-guts/assets/js/utils/form_helpers/form_helper_factory.js
website-guts/endpoint-mocks/createAccountInvalidEmail.json

Two changes:
1. Adds a callback to the modal open function
2. Manually activates the new email verification experiment when someone opens the sign up modal window on the homepage
3. Adds a little bit of code that handles not-real email address
#1 and #2 are not testable in local dev.
To test #3, change 83-92 in grunt/connect.js to:
```js
} else if(req.url === '/account/create') {
if(req.body.email !== 'david.fox-powell@optimizely.com') {
res.cookie('optimizely_signed_in', '1', {httpOnly: false});
res.writeHead(400, {'Content-Type': 'application/json'});
res.end( grunt.file.read('website-guts/endpoint-mocks/createAccountInvalidEmail.json') );
} else {
res.writeHead(400, {'Content-Type': 'application/json'});
res.end( grunt.file.read('website-guts/endpoint-mocks/accountExists.json') );
}
} …
```

Manually activate email verification experiment.

---

website-guts/assets/css/pages/opticon-speakers.scss
website-guts/assets/css/styles.scss
website/opticon/speakers/index.hbs
website/opticon/speakers/speakers_data.yml

The link optimizely.com/opticon/speakers is still in the wild and we need to let users know that the call for speakers is closed. This PR does that.

Add close speaker yml message, style, and markup

---

website-guts/assets/js/pages/opticon.js
website-guts/helpers/helper-isDest.js
website-guts/templates/layouts/opticon.hbs

@stewsmith I made a mistake, in the layout you have to use `page.dest` and in there its a string not an object like in a page. 
- add another directory called `opticon-2` or whatever.
- copy the opticon page in there
- start the server and go to `/opticon`. Smooth scroll should work
- go to `/opticon-2` and links should redirect to opticon at the selected links place on the page.

add dest checking helper and smooth scroll for opticon nav

---

bower.json
website-guts/assets/js/global.js
website-guts/assets/js/layouts/trial-form.js
website-guts/assets/js/om/layouts/original.js
website-guts/assets/js/pages/webinar.js
website-guts/assets/js/utils/form_helpers/create_account_helpers.js
website-guts/assets/js/utils/form_helpers/form_helper_factory.js
website-guts/assets/js/utils/form_helpers/mobile_mvpp_helper.js
website-guts/assets/js/utils/form_helpers/seo_helpers.js
website-guts/assets/js/utils/form_helpers/signin_helpers.js
website-guts/assets/js/utils/oform_globals.js

Updated Oform to 3.0.0, which is a non-backwards compatible release. This is the version that the OM page uses so it's pretty stable.
To verify that this works you should:
1. Run `grunt test`
2. Manually test /resources/live-demo-webinar (this doesn't have UI test)
Might also be good to run through each flow yourself in Chrome to see if any errors pop up in the console.

Change Oform code for newer version.

---

website-guts/assets/js/om/utils/oform-globals.js
website-guts/assets/js/utils/oform_globals.js

This PR removes the `munchkin` calls we were making to `associateLead` because this is now being taken care of by segment.
In addition if fixes two errors on the `om` for the `err` variable and the `XHR` property on the `XHRevent` object

remove munchkin from track lead

---

website-guts/assets/js/global.js

This is a bit difficult. You can put a breakpoint in the global cookie removal function and check properties. Probably it won't be called though because the `amplitude` cookie won't exist in dev. If you have the `amplitude` cookie in prod probably best to just call the jQuery cookie removal function with the options specified.

add cookie removal script for amplitude

---

Gruntfile.js
grunt/open.js
package.json

Last Thursday I deployed a bug to production that broke all leads on the /om/free-trial page. The new OM tests would have caught this, but for some reason neither David nor I ran the OM tests on the branch so we didn't catch the bug. Obviously we can't afford anymore lead bugs so we need to ensure that the OM tests are always run on every PR.
To prevent this from happening in the future, this PR integrates the OM tests into the `grunt test` and `grunt ui-test` tasks. That means you can run the OM tests in three different ways:
1. `grunt test` while your local sever is NOT running
2. 'grunt ui-test` while your local server IS running - this run all UI tests
3. `grunt ui-test:om` while your local server IS running - this runs only the OM tests
There isn't much of a change for anyone here. …

Add om-tests to grunt test and grunt ui-test.

---

website-guts/assets/css/pages/opticon-about.scss
website/opticon/about/index.hbs
website/opticon/about/opticon_about.yml

We need a link to the sponsorship prospectus. This PR replaces the Opties paragraph (which lacks a CTA) with the prospectus.

Add prospectus to about page

---

website-guts/helpers/helper-debug.js
website-guts/helpers/helper-isUrlLike.js
website-guts/templates/layouts/partners.hbs

###Purpose
- not allow marketers to enter invalid input for `kb_article` parameter. This is the link to the external article button.
- if the url is not valid https, http, or //something.co the button will not be displayed
###Test
Please test this, the regex was breaking Node build previously
- just run `grunt server as normal`
- got to `partners/technology/liveramp/` and check there is no "Get implementation guide" button
- got to another technology partner page and ensure the button is there with functioning link

add urlLike helper to check for valid KB article url

---

website/index.hbs

Added Google+ publisher meta tag, which links our homepage to our Google+ page

Adding Google+ publisher code to homepage

---

website-guts/assets/css/modules/header.scss

Main nav top level li's had an underline on hover
- hover pricing or jobs, these were the problem items

remove underline for main-nav top level menu items

---

Gruntfile.js
configs/uiTestConfig.js
package.json

This PR addresses upgrading our Nightmare ^1.7 module and PhantomJS to 2.0.0. We are still pulling Nightmare from my github due to
https://github.com/segmentio/nightmare/issues/120
And we are now pulling the PhantomJS binary from my github because the current PhantomJS node module won't update until PhantomJS 2.0.0 is stable
https://github.com/Medium/phantomjs/issues/288
I adjusted the build script of this module to pull the only working PhantomJS binary for MacOSX I could find. Hopefully when Nightmare and PhantomJS get their act together we can stop pulling from my GH.
```bash
rm -rf node_modules && npm cache clear && npm i
```
or add this alias to your .zshrc 
```
alias rmall='nvm use 0.10 && rm -rf node_modules && npm cache clear && npm i'
```
also if you are using nvm and have a …

upgrade to phantom 2.0 and nightmare 1.7

---

website-guts/assets/css/modules/footer.scss

This PR revert inappropriate color for linkedin social media icon in the grey footer https://github.com/optimizely/marketing-website/pull/937.

hide linkedin social icon in footer

---

website-guts/assets/js/utils/oform_globals.js

on all benefits pages
- /demo
- /enterprises
- /ecommerce
the `initContactForm` method was referencing a selector for `InboundLeadformType` that didn't exist
submit form on any of these pages and put a breakpoint in the `w.optly.mrkt.utils.oform.initContactForm` method and check the object that is being passed to the `identify` method

fix selector for leadform type and add fallback

---

website-guts/templates/components/modals/downgrade_plan.hbs
website-guts/templates/components/modals/pricing_plan_signup_thank_you.hbs

This PR addresses `tr` helper not removing backslash escape characters that is messing with translation strings and causing bad UX.
Go to /pricing and inspect 
- `id="pricing-plan-signup-thank-you-cont"`
- `id="downgrade-plan-cont"`
And make sure there are no remaining `\` characters.

remove tr helper from pricing modals

---

.hound.yml
.scss-style.yml

For a more complete listing see: 
[Linting Options](https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md#urlquotes)
Reports when you use improper spacing around ! (the "bang") in !important and !default declarations.
Prefer hexadecimal color codes over color keywords.
Prefer color literals (keywords or hexadecimal codes) to be used only in variable declarations. They should be referred to via variables everywhere else.
Prefer `//` comments over `/* ... */`.
Reports @debug statements
Reports when you define the same property twice in a single rule set.
Reports when you have an empty rule set.
Checks if hexadecimal colors are written in lowercase.
Ensure hexadecimal colors are valid
Use two spaces per indentation level.
Reports when you define the same selector …

Hound config

---

website-guts/templates/layouts/jobs.hbs

In Assemble v6 migration messed referencing external yml data for jobs page.
check staging http://optimizely-marketing-site-staging.s3-website-us-east-1.amazonaws.com/dfoxpowell/fix-jobs-layout/jobs/

Change external yml reference in jobs layout

---

grunt/assemble/plugins/smartling.js

This PR addresses https://optimizely.atlassian.net/browse/MKT-1696 requesting pages with a `TR_seo_title` key to have ` - Optimizely` appended to the value.
Find a page like /partners/solutions and inspect that the title in the browser tab got appended with ` - Optimizely`.
Now check a page with no `TR_seo_title` key such as the homepage and inspect that the title in the tab is `'Optimizely: Make every experience count'`

add default seo title suffix

---

grunt/assemble/index.js
grunt/assemble/plugins/seo-title.js
grunt/assemble/plugins/smartling.js

Reverts https://github.com/optimizely/marketing-website/pull/1018 to account for new logic in https://optimizely.atlassian.net/browse/MKT-1696
run `grunt server` 
check that pages with no `TR_seo_title` have in their tab
- if `TR_visible_title` is present, this will be concated with `- Optimizely`
- if `title` is present (partners pages) the dirname is being used, striped of slashes, capitalized, and concated with `- Optimizely`

add plugin for seo title

---

website/opticon/agenda/agenda_data.yml

The Roundtable discussion on the Option Agenda needs to be on Day 1 of Opticon

Move roundtable discussion

---

grunt/sass.js

`path.join` was breaking production paths because it was removing one of the slashes from double forwardslash asset path

remove path.join from custom sass function

---

grunt/assemble/plugins/seo-title.js
website/opticon/index.hbs

Opticon is showing up as "OptiCon" in the Google search results. Fixing this by explicitly setting a title via TR_seo_title.

Adding TR_seo_title to Opticon homepage

---

website-guts/templates/layouts/wrapper.hbs

This PR adds the og_image tag. Currently when posting to linkedin, a starbucks image appears as the image. Now an Optimizely image will appear.
To test: go to linkedin and click share a post. Paste in the staging url and verify the image being pulled in is the following:
https://s3.amazonaws.com/cloud_cannon_production/optimizely-marketer-assets.cloudvent.net/raw/global/optly_social_share.png?AWSAccessKeyId=AKIAIJL2YOFJV3LTZJDQ&Expires=1430849680&Signature=BTL7OJieev%2FZP4LeeDgWXCPSNO4%3D

Add og image to wrapper

---

grunt/assemble/index.js
grunt/assemble/plugins/seo-title.js

I made a mistake in https://github.com/optimizely/marketing-website/pull/1057 and accidentally reverted the ability to add a custom SEO default title.
go to https://www.optimizelystaging.com/dfoxpowell/fix-seo-title/partners/solutions and click on individual partners page. Seo title in the browser tab should correspond to the filename

fix custom seo title

---

grunt/filerev.js
package.json
website-guts/templates/layouts/wrapper.hbs

This is in response to JIRA issue https://optimizely.atlassian.net/browse/MKT-1693
Now we are sourcing the favicon from a path rather than relying on it being in the root of the website. 
In production path should be https://du7782fucwe1l.cloudfront.net/img/favicon.ico
- check in staging if favicon works
- locally run `grunt build` and check in one of the html templates `<head>` that favicon link is correct ` <link rel="shortcut icon" href="//du7782fucwe1l.cloudfront.net/img/favicon.ico/img/favicon.ico">`

add relative path to favicon

---

package.json

- stop pulling grunt sass from GitHub directly

bump grunt sass to 1.0.0

---

website-guts/assets/css/pages/opticon-homepage.scss
website/opticon/global_opticon_data.yml

Trulia sent us an updated logo to be used on the Opticon homepage.

Update trulia logo on opticon homepage

---

website-guts/templates/layouts/faq.hbs
website-guts/templates/layouts/wrapper.hbs
website-guts/templates/om/layouts/wrapper.hbs
website/nonprofits/index.hbs
website/press/press.yml
website/resources/resources-list/ab_advantage/index.hbs
website/resources/resources-list/ab_testing_goes_mobile/index.hbs
website/resources/resources-list/countdown_to_christmas/index.hbs
website/resources/resources-list/testing_team_structures/index.hbs
website/statistics/statistics_data.yml

The blog has now moved from HTTP to HTTPS, updating the links in the header & footer to reference the new HTTPS url.

Switching Blog Link to HTTPS

---

website-guts/assets/js/utils/no-global/get-language-key.js
website-guts/assets/js/utils/oform_globals.js
website-guts/helpers/stringifyJS.js
website-guts/templates/layouts/wrapper.hbs

@arthuracs @4vanger 
Adds temporary tracking of language key for `/account/create` based upon `ccTLD`.
- only works for requests made to `/account/create` (ie no `/account/free_trial_create`. @arthuracs let me know if this should be added as well but it would mean updating another endpoint.
- go to any page that uses `/account/create` i.e. homepage, mobile page
- preserve the log in chrome network and inspect the request payload sent
- should see a `locale` key
- default is `us_EN`, unfortunately we cannot test this in staging for `ccTLD` unless you have some good ideas of how.
staging url: https://www.optimizelystaging.com/dfoxpowell/language-selection-cctld/

add locale tracking data to oform middleware

---

package.json
website-guts/assets/js/layouts/trial-form.js

This is defensive coding after adding webpack to the marketing site. Adding the es-5 shim for older browser support on /free-trial
- run `ui-test` locally
- submit the form and check validation errors
@stewsmith please review

add es5 shim for /free-trial

---

website-guts/assets/js/head-scripts/user-state.js

This PR addresses https://optimizely.atlassian.net/browse/AI-386#add-comment since the app/www split.
Until we split to subfolders the `optimizely_signed_in` cookie is not being set on ccTLD. Therefore, logged in users on the marketing site will not have their info populated in the utility nav.
This fix is the same behavior that happens currently on staging. Requests will always be made for account info and experiment info. If the user is not logged in `/account/info` responds with an object containing null values, whereas the request for last five experiments fails.
*Note*: these changes should be removed after deployment of subfolders
this is pretty much impossible to test until we get it into production. Test in staging https://www.optimizelystaging.com/dfoxpowell/hotfix-login-cctld/ …

allow requests for user info to be made without cooking on cctld

---

website-guts/assets/js/layouts/opticon.js

Right now we're losing the query params if someone clicks around the Opticon site. This PR appends the query links to all anchor tags `href` attribute.
To test:
1. Visit staging`/opticon?test=true`
2. Click other navigation links and verify the param is still there.
3. Click on the register button and verify params are on eventbrite url

Append query params on anchor tags for opticon

---

website-guts/templates/layouts/wrapper.hbs
website/index.hbs

The meta description is used to tell Google what the page is about and is often displayed as the description in the search results.
If a custom description is set, then the page should include should display the meta description so that Google can show the optimized snippet.
However, if a custom description does not exist, then no meta description should be displayed so that Google can generate it's own description for the page.

Remove default meta description

---

website-guts/assets/js/components/modal-devsignup.js
website-guts/assets/js/pages/homepage.js
website-guts/templates/components/modals/dev_signup_modal.hbs
website-guts/templates/layouts/wrapper.hbs
website/index.hbs

Create the developers account signup form at the marketing site for now since we encounter an HTTPS setup issue for the new developers site which prevents the site from sending CORS requests to our GAE app.
request review: @stewsmith @tscanlin

Add developers account signup form

---

website/partners/solutions/digitaslbi-hong-kong/index.hbs
website/partners/solutions/goldbach-interactive/index.hbs
website/partners/solutions/hop-online/index.hbs
website/partners/solutions/mccann-connected/index.hbs

Right now some of the partners are not sorting correctly. This PR fixes that by prefixing `locations`, `region`, `state`, `city`, and `country` with`TR_`
To test, go to production and sort by "EMEA - Germany". Notice goldbach-interactive is not there. Try the same thing on staging and notice goldbach-interactive is there.

TR_ on partners fix

---

website/features-and-plans/global_features.yml
website/partners/technology/join/join_data.yml
website/plans/global_faq_section.yml
website/solutions/solutions.yml

to make sure links correctly resolve on international domains.
@stewsmith can you review? The references to www.optimizely.com jump visitors on international domains back to the English site. If we just make it a relative link, they'll stay on the international site. I fixed it in the places I could find, but please make sure to use relative links for any internal links.
@KarenLoughrey this should address the link issues you were seeing on https://www.optimizely.de/solutions/ and other international domains.

Remove hardcoded references to optimizely.com

---

website/partners/technology/join/index.hbs
website/partners/technology/join/join_data.yml

Add a swap tag and id to /partners/technology/join so a section doesn't show up in japan.
https://optimizely.atlassian.net/browse/MKT-2075
To test: go to /partners/technology/join and inspect the last benefit. It should have a class of `SL_swap` and id of `JP_tech_join`

MKT-2075 -- Add swap tag to tech partners signup page

---

website-guts/assets/js/pages/solutions.js

On /solutions when the user clicks on one of these:
we need to track it.
I've verified this is going through to segment:

Add reporting to tab click on solutions

---

website-guts/templates/partials/contact_form.hbs

"We'll be in touch shortly" typo:

Fix typo on contact thank you

---

sitemap.xml

@stewsmith @ihsekat - This PR just removes white space from the sitemap.xml file.
`<xhtml:link rel="alternate" hreflang="en" href="https://www.optimizely.com/" />` becomes `<xhtml:link rel="alternate" hreflang="en" href="https://www.optimizely.com/"/>`
File size goes from 473,528 bytes -> 469,629 bytes.

Removed whitespace from sitemap.xml file.

---

website/free-trial/index.hbs

The number of experiments run is very far off reality plus we're not communicating this anywhere else on the site. Jessie asked for it to be removed. Currently we don't see this on the US website due to an experiment running on that page - but the intl sites are showing the original with this data.

Jessie wants the social proof to be removed

---

website/careers/index.hbs

currently the default text for a careers page is generic. this is a great place for us to have a nicer message: we're reaching out to potential employees after all.

Update social share text on careers page

---

website-guts/templates/partials/faq_section.hbs
website/plans/index.hbs

This PR is to temporarily hide untranslated plans page content. A separate PR will be created to translate this content.

hide untranslated content on plans page

---

website-guts/assets/css/components/feature-list.scss

Remove extra left margin from span on /plans

---

website-guts/assets/js/utils/oform_globals.js

Marketing Automation has been missing "lead_source___c" for a long time and we couldn't for the life of us figure out why, since it was always in our Segment debugging. Looks like we weren't seeing a discrepancy in our spelling. 
@stewsmith can you please review?
I think this typo catch should help.
@allisonsparrow once this is merged, can you keep your eye peeled going forward to see if this form field is now being populated in Marketo? I think this should do the trick.
This should address issues listed on https://optimizely.atlassian.net/browse/MKT-2009

Fix typo from lead_scource to lead_source
