- website/communities/communities.yml
> Fix some typos

- website/contact/index.hbs
- website/opt_out/index.hbs
[JIRA ticket here](https://optimizely.atlassian.net/browse/MKT-888)
> MKT-888 -- Remove references to hello@ on contact and opt_out pages

- website/partners/technology/ptengine/index.hbs
@teeyoutan please review changes - thanks!
> Edit summary

- website/resources/ios-ab-testing/index.hbs
> Added What Is iOS A/B Testing SEO page

- website-guts/assets/css/components/modals.scss
- website-guts/assets/css/helper-classes.scss
- website-guts/assets/css/layouts/benefits.scss
- website-guts/assets/css/layouts/jobs.scss
- website-guts/assets/css/main.scss
- website-guts/assets/css/modules/forms.scss
- website-guts/assets/css/modules/opticon-header.scss
- website-guts/assets/css/modules/type.scss
- website-guts/assets/css/pages/live-demo-webinar.scss
- website-guts/assets/css/pages/mvt.scss
- website-guts/assets/css/pages/opt-out.scss
- website-guts/assets/css/pages/opticon-confirmation.scss
- website-guts/assets/css/pages/opticon-speakers.scss
- website-guts/assets/css/pages/opticon.scss
- website-guts/assets/css/pages/press.scss
- website-guts/assets/css/pages/sample-size-calculator.scss
- website-guts/assets/css/pages/split-testing.scss
- website-guts/assets/css/styles.scss
- website-guts/assets/css/variables.scss
- website-guts/templates/layouts/opticon.hbs
- website-guts/templates/layouts/wrapper.hbs
- website/nonprofits/index.hbs
- website/opticon/index.hbs
- website/opticon/opticon_data.yml
- website/opticon/speakers/confirmation/index.hbs
- website/opticon/speakers/index.hbs
- website/opticon/speakers/speakers_data.yml
This code adds back what was reverted last night plus the white nav correction.
> Add opticon back with corrected nav styling

- website-guts/assets/css/modules/opticon-header.scss
> Change top margin to vertically align nav options

- website-guts/assets/css/pages/sample-size-calculator.scss
capitalize first letters of sample size calculation
@beso323 
current production hash for css: `a5ea71dd`
expected hash from local build: `70356819`
> Test build for Jenkins Deploy

- website-guts/assets/css/pages/sample-size-calculator.scss
change font size and weight for jenkins test build
locally I get this hash for CSS `a98e7de4`
@beso323
> second test for Jenkins build

- website-guts/assets/js/pages/opticon.js
- website/opticon/index.hbs
https://optimizely.atlassian.net/browse/MKT-934
This PR is so we can see how many people are buying tickets through the butterbar in the product.
It passes the url param aff=butterbar on to eventbrite.
> MKT-934 -- Send butterbar param to eventbrite when present on /opticon

- website/statistics/index.hbs
@kylerush @mikecdavis
Fixing regression from [commit 1a9697014fe780124b749d5ef81bde79a4dbccd4](https://github.com/optimizely/marketing-website/commit/1a9697014fe780124b749d5ef81bde79a4dbccd4).
> Fix /statistics styling

- website-guts/templates/layouts/wrapper.hbs
Allows us to target anonymous visitors using Demandbase data :bowtie:
> Add Demandbase snippet.

- website/statistics/statistics_data.yml
I'm not sure why we're making such a misleading comparison.
BTW the footnote doesn't actually show up.  There's just a hidden div with strangely munged text...
> Fix stats comparison

- website/statistics/statistics_data.yml
Change was made live before content was reviewed by marketing
> Revert "Fix stats comparison"

- website/partners/solutions/prodigal-solutions/index.hbs
@teeyoutan please review new partner
> Add Prodigal Solutions partner

- website-guts/assets/css/pages/opticon.scss
- website/opticon/index.hbs
- website/opticon/opticon_data.yml
[Marketing Eng Ticket](https://optimizely.atlassian.net/browse/MKT-1008)
[Design Ticket](https://optimizely.atlassian.net/browse/UED-679)
Create a section for the Marc Andreeseen announcement.
Also add a tab which links to the 'Justify your Trip' pdf
> Opticon updates -- Andreeseen Section and Justify Your Trip

- website/statistics/index.hbs
- website/statistics/statistics_data.yml
@dtothefp can you review?
@KarenLoughrey this should cover all the swaps you want to do
> Add Smartling content swaps to Stats Engine landing page

- website/opticon/index.hbs
We want the registration section towards the top so this PR does that.
> Move registration section towards the top

- website/partners/technology/episerver/index.hbs
@juliritchie for your review
@teeyoutan what is the eta on the logo?  Should we be committing logos as part of the same pull request to avoid dependencies?
> Partner directory entry for EPiServer

- website-guts/assets/js/layouts/trial-form.js
- website-guts/assets/js/om/layouts/original.js
Per MKT-1126
To test:
1. Open your host file
2. Point both wwww.optimizely.com and www.optimizely.de to your local server. Example: 
```
0.0.0.0 www.optimizely.com
0.0.0.0 www.optimizely.de
```
3. Save the changes to your host file
4. Visit both www.optimizely.de:9000/free-trial and www.optimizely.com:9000/free-trial
5. Submit the form. You should be taken to the german editor on .de when you submit on the German page and the US editor on .com when you submit on the .com domain.
6. MAKE SURE YOU REVERT THE CHANGES TO YOUR HOST FILE
> Adjust PPC redirect.

- website-guts/templates/partials/ad_tags.hbs
[MKT-822](https://optimizely.atlassian.net/browse/MKT-822)
> MKT-822 -- remove only google adwords script

- website-guts/assets/css/pages/features-and-plans.scss
- website-guts/assets/css/pages/pricing2.scss
- website-guts/assets/js/pages/features-and-plans.js
- website-guts/assets/js/pages/pricing2.js
- website-guts/endpoint-mocks/accountInfo.json
- website-guts/templates/partials/faq_section.hbs
- website-guts/templates/partials/feature_list.hbs
- website/feature-list/feature_list.yml
- website/features-and-plans/features.yml
- website/features-and-plans/index.hbs
- website/pricing2/index.hbs
Changes:
- Adds a global variable for scroll tracking goal for the experiment
- Cleans up some spacing on type
- Use `&raquo;` instead of `>>`
- Added "Your current plan"
- Prevent downgrade from enterprise
> Fix some things.

- website-guts/assets/css/pages/statistics.scss
- website/statistics/index.hbs
https://optimizely.atlassian.net/browse/MKT-1013
> MKT-1013 -- Stats Page design fixes

- website-guts/assets/css/components/feature-list.scss
- website-guts/assets/css/pages/feature-list.scss
- website-guts/assets/css/pages/pricing.scss
show and hide plan specific content on the feature list, not individual pages
> Hide 'your current plan' on feature-list

- website-guts/assets/js/global.js
- website-guts/assets/js/layouts/trial-form.js
- website-guts/assets/js/om/global.js
- website-guts/assets/js/om/layouts/original.js
- website-guts/assets/js/om/test/test.js
- website-guts/templates/layouts/wrapper.hbs
- website-guts/templates/om/layouts/wrapper.hbs
With this change we can start monitoring the amount of time it takes the Optimizely snippet to load using Google Analytics user timings.
> Add user timing for Optimizely snippet.

- website/resources/online-marketing/index.hbs
New page under /resources for SEO purposes.
> Create new "What is Online Marketing?" page

- website/partners/technology/Lytics
- website/partners/technology/lytics/index.hbs
@dtothefp @julieritchie Trying this again, since it looks like the branch on my last try was messy. Let me know if this works.
Also, heads up that for the logo, I put in the link from Cloud Cannon, but I'm not sure if this is the correct way to add the logo. If not, please let me know how to do so. Thanks!
> Create Lytics Listing in Partner Directory

- website-guts/assets/css/pages/mobile.scss
- website/mobile/index.hbs
- website/mobile/mobile_page_mvpp_data.yml
making some changes to the mobile landing page:
1. Removing the "mobile metrics" section from the page
2. Adding two strategy article links to the mobile testing ideas section
> mobile landing page updates

- website-guts/assets/js/components/modal-contact-sales.js
- website-guts/assets/js/pages/features-and-plans.js
- website-guts/assets/js/pages/pricing.js
- website-guts/assets/js/utils/form_helpers/create_account_helpers.js
This PR just cleans up the pricing JS a little bit. Nowhere is `data` actually used so we don't need to have it in the helper or load functions.
> Minor cleanup on pricing page.

- website-guts/assets/js/components/modals.js
- website-guts/assets/js/global.js
- website-guts/assets/js/pages/homepage.js
- website-guts/templates/layouts/wrapper.hbs
Changes:
1. Adds Google Analytics user timing the modal helper to track how long a modal window is open before it is closed. This will be helpful for optimization purposes.
2. Fixes a spelling error on existing user timing events. Changes `TimeingLabel` to `TimingLabel`.
3. Adds engagement, focus, and blur tracking on sign up form on the homepage.
4. Fixes a minor JSHint issue in the wrapper. Changes `(new Date)` to `(new Date())`.
> Add form engagement tracking.

- website-guts/assets/css/pages/features-and-plans.scss
- website-guts/assets/css/pages/pricing.scss
- website/features-and-plans/features.yml
- website/features-and-plans/index.hbs
- website/pricing/index.hbs
- website/pricing/pricing.yml
@stewsmith Hey I deleted the asterisk from the pricing.yml file, JIRA ticket MKTG 1481
> Removed android coming soon message

- website/partners/solutions/conversionlift/index.hbs
Logo link:  refresnow to cloudcannon file
Website link: now without https://
> Solution Partner Conversionlift: Updated Logo Link and Website Link

- website/partners/solutions/conversionlift/index.hbs
- website/partners/solutions/first-australia/index.hbs
- website/partners/solutions/prodigal-solutions/index.hbs
Partner stars were out of order. This PR puts partners in order by star values.
> Change priority so stars are in order

- website-guts/assets/css/layouts/trial-form.scss
remove fixed width on ppc form cont and make input width 100%
> Fix ppc broken styles

- website/opticon/about/opticon_about.yml
About page has a bad href. This PR closes the href quote.
> End quote on href on Opticon/about

- website-guts/templates/layouts/wrapper.hbs
- website/index.hbs
- Added a handle called "meta_tags" to the wrapper
- Added the Pinterest verification meta tag to the homepage via "meta_tags" handle.
> Takeshi pinterest verification

- website/opticon/speakers/speakers_data.yml
> Opticon typo

- website-guts/assets/css/modules/opticon-footer.scss
- website-guts/templates/layouts/opticon.hbs
We need the sponsor prospectus displayed more prominently. This PR puts a link to the pdf in the header. 
It also changes the footer font-size in tablet.
> Add sponsor prospectus to header

- website/mobile/mobile_page_mvpp_data.yml
this feature is not supported by the product
> remove multichannel experiences from mobile LP

- website/partners/technology/sessioncam/index.hbs
@julieritchie @kellyfinn Please review it
> Content review

- website/partners/technology/dialogtech/index.hbs
- website/partners/technology/ifbyphone/index.hbs
@julieritchie Given Ifbyphone's rebranding to DialogTech, updating their name, website, and company description here. I will send you their new logo via e-mail as well. Thanks!
> Update Ifbyphone to DialogTech in Partner Directory

- website-guts/templates/layouts/wrapper.hbs
Structured data for social profiles: https://developers.google.com/structured-data/customize/social-profiles
> Added Google+ Schema To Social Links

- .gitignore
- website-guts/assets/css/layouts/seo-layout.scss
This PR addresses broken form style for SEO form on SEO layout
- `/ab-testing`
- `ios-ab-testing`
- etc...anything with the `seo` layout
> dislpay labels block and input width 100% for seo page form

- website/partners/solutions/adept-marketing/index.hbs
@dtothefp @stewsmith @julieritchie 
This is ready
> Updated Adept Partner Logo

- website/resources/resources-list/retail-guide/index.hbs
added ecommerce ebook to resources page
> Ecommerce Ebook

- website/partners/solutions/smart-internet-media/index.hbs
Changed region to EMEA - Netherlands so will be found when filtering on this region! Made this minor mistake at the first try :)
@julieritchie, @kellyfinn please review, THANKS!
> Update on region for smart-internet-media/index.hbs

- website/partners/technology/parsely/index.hbs
- updated logo it was incorrect
- the last branch was created improperly so I created this one
@clarissabee @kellyfinn please review. This reverts https://github.com/optimizely/marketing-website/pull/951
> create new pars.ly dir

- website/partners/technology/inspectlet/index.hbs
@julieritchie @kellyfinn Sent you the logo for this via e-mail. No KB article yet for this one.
> Create Inspectlet Listing in Partner Directory

- website-guts/templates/client/eventDisplay.hbs
https://optimizely.atlassian.net/browse/MKT-1643
> MKT-1643 -- Close quote for events

- test/misc/custom-dimension-spec.js
- website-guts/templates/layouts/wrapper.hbs
Adds a "Signed in" custom dimension with values of "true" or "false". This will help us determine how many visits to the marketing website are from signed in visitors. I added a test for this. All tests pass with `grunt test`.
> Add signed in custom dimension.

- website/index.hbs
The ethnio survey is showing up on locale domain and it shouldn't. I'm going to remove it in the codebase and inject it using Optimizely.
> Remove ethn.io

- website/partners/technology/dialogtech/index.hbs
- website/partners/technology/episerver/index.hbs
- website/partners/technology/freespee/index.hbs
- website/partners/technology/google-analytics/index.hbs
- website/partners/technology/moat/index.hbs
- website/partners/technology/parsely/index.hbs
- website/partners/technology/ptengine/index.hbs
- website/partners/technology/qualaroo/index.hbs
- website/partners/technology/segment/index.hbs
- website/partners/technology/sessioncam/index.hbs
- website/partners/technology/skymosity/index.hbs
@dtothefp @stewsmith @julieritchie In order to make the Technology Partners appear in alphabetical order, the Priority values need to be updated for various partners. I've updated I believe all needed in this branch.
> Update Technology Partners to appear in alphabetical order

- website/partners/technology/krux/index.hbs
@julieritchie @kellyfinn Here's the Krux listing. Will e-mail you the logo shortly. No KB article for this yet either.
> Create Krux Listing in Partner Directory

- website/partners/solutions/fresh-egg/index.hbs
Phone number format seems off and is different than the one listed on their website.
Please confirm @kellyfinn
> Fixed phone number

- website/jobs/index.hbs
> Updating Title

- website-guts/templates/layouts/wrapper.hbs
Link to /success not success.optimizely.com in footer
https://optimizely.atlassian.net/browse/MKT-1714
> MKT-1714 -- Customer Success footer link

- website/partners/solutions/webarts/index.hbs
@kellyfinn  hey kelly, this is the PR for solution Partner Web Arts. (logos are already resized and uploaded in Cloudcannon)
Thanks for your help!
Cheers,
Werner
> New solution partner entry: Web Arts AG

- website/partners/solutions/uservalue/index.hbs
@kellyfinn hey kelly, this is the PR for solution partner Uservalue.
Cheers,
Werner
> Add partner to Partner Directory: Wdecker/partnerdirectory add uservalue

- grunt/webpack/index.js
- grunt/webpack/make-webpack-config.js
Reverts optimizely/marketing-website#1010
> Revert "move inject filename loader from preloaders to loaders"

- package.json
Reverts optimizely/marketing-website#1008
> Revert "Log inject filename info to jenkins console"

- website/partners/solutions/conversion-factory/index.hbs
Conversion Factory is now Conversion- new logo and contact info replaced old info.
> Updated logo and contact info for Conversion

- website/partners/solutions/catchi/index.hbs
- website/partners/solutions/wider-funnel/index.hbs
Both partners updated to 3 stars.
> Update Catchi and Widerfunnel stars

- website/opticon/agenda/agenda_data.yml
- website/opticon/agenda/index.hbs
Updates to the agenda:
1. Titles
2. Locations
3. Speakers
> Bulk update opticon agenda

- website/partners/solutions/uservalue/index.hbs
Updated logo, link and address
> Updates to Uservalue

- website/contact/index.hbs
Expanded our contact page as we're growing globally. Added phone numbers to all our EMEA offices and added the address of the official German office.
> Adding new addresses and phone numbers

- website/partners/solutions/deg/index.hbs
- website/partners/solutions/sell-points/index.hbs
- website/partners/technology/dialogtech/index.hbs
- website/partners/technology/freespee/index.hbs
- website/partners/technology/sessioncam/index.hbs
Updated logo links for SessionCam, FreeSpee, DialogTech, DEG, and Sellpoints
> Updated broken logo links

- website/opticon/event-info/opticon_about.yml
Changing the hotel info to reflect one hotel being booked.
> Change hotel info on event info

- website-guts/assets/css/pages/opticon-sponsors.scss
- website/opticon/sponsors/sponsors_data.yml
Decibel Insight and Blue Acorn are now sponsors so we gotta add them to the page.
Still waiting on descriptions.
> Add decibel insight and blue acorn to sponsors

- website-guts/assets/css/pages/homepage.scss
- website/index.hbs
Adds an advertisement for Opticon on www.optimizely.com
> Opticon Homepage Ad

- website/press/index.hbs
changes in datejs broke dates on press page
> account for changes in datejs

- website/index.hbs
Ownership verification for Bing Webmaster Tools
> Bing Webmaster Tools Verification

- website/opticon/agenda/agenda_data.yml
Adding speakers: Ash, Ryan Garner
Removing: Jevan Soo
> Agenda update for speakers

- website/opticon/sponsors/sponsors_data.yml
This adds descriptions on the modals for blue acorn and decibel
> Add descriptions for blue acorn and decibel

- website/partners/solutions/mindberry/index.hbs
- website/partners/solutions/uservalue/index.hbs
> Update to Mindberry and Uservalue

- website-guts/assets/js/components/utility-nav.js
- website-guts/assets/js/utils/form_helpers/signin_helpers.js
- website-guts/templates/client/loggedInUtilityNav.hbs
1. Change "Dashboard" to "Home"
2. Remove the experiments dropdown
3. Add link to /appsettings under account
https://optimizely.atlassian.net/browse/MKT-1892
> MKT-1892 -- Logged in Nav More like Product

- grunt/config.js
- `linkPath` in staging had an extra trailing slash
> fix linkPath in staging

- website-guts/assets/js/pages/pricing.js
@dtothefp & @stewsmith this adds the ability to trigger the contact sales modal on the pricing page.
> add url parameter to show contact sales modal on pricing page

- website-guts/assets/css/pages/opticon-sponsors.scss
- website/opticon/sponsors/sponsors_data.yml
1. Add Tealium logo
2. Add Amplitude logo
3. Change roboboogie logo
4. Adjust logo width
> Opticon sponsor updates

- grunt/assemble/plugins/translation-utils/smartling-upload.js
- package.json
uses SL_PREFIX env variable to override filename prefix when uploading to smartling
> code to use new-format smartling configs

- website-guts/assets/css/layouts/opticon.scss
- website-guts/assets/css/pages/opticon-homepage.scss
The padding on the opticon titles is a bit off. This PR fixes that.
> Fix padding on opticon titles

- website/opticon/agenda/agenda_data.yml
> Replace elance with Upwork

- grunt/copy.js
- sitemap.xml
copies from root of repo to dist
check the jenkins staging workspace that `sitemap.xml` gets copied to `dist`
addresses https://optimizely.atlassian.net/browse/MKT-1771
@ihsekat
> add sitemap.xml

- website/opticon/index.hbs
Updating title to be more mobile friendly
> Title Update

- website-guts/assets/css/layouts/jobs.scss
- website-guts/assets/js/pages/jobs.js
- website/jobs/index.hbs
- website/jobs/jobs.yml
@stewsmith Changes made as discussed
> Updated employee quotes and faces on jobs page

- website/opticon/speakers/speakers_data.yml
staging here: https://www.optimizelystaging.com/ssmith/opticon-speaker/opticon/speakers
@yesplease Can you review?
> Add michelle to Opticon speakers

- website-guts/assets/css/layouts/opticon.scss
- website-guts/assets/js/pages/opticon-sponsors.js
1. bigger font on opticon modals
2. bigger bg images
3. sponsor modal doesn't scroll to top anymore
> Opticon Modal improvements

- website-guts/assets/css/pages/opticon-homepage.scss
- website/opticon/global_opticon_data.yml
- website/opticon/index.hbs
> Opties Finalists Announcement box

- website/opticon/agenda/agenda_data.yml
Adds the word room to the locations in the Opticon agenda.
> Add 'room' to talk locations

- website-guts/assets/css/pages/opticon-sponsors.scss
- website/opticon/sponsors/sponsors_data.yml
Add demandbase and analytics pros
> Add Opticon Sponsors

- website/opticon/agenda/agenda_data.yml
- website/opticon/speakers/speakers_data.yml
Removed Matty from agenda
Removed Deepa from agenda and from speakers page
> Speakers page and agenda updates

- website/success/success.yml
> Success images hotfix

- website-guts/templates/layouts/wrapper.hbs
- website-guts/templates/om/layouts/wrapper.hbs
link agencies to partners/solutions
> Footer /partners/solutions link

- website/partners/solutions/33-sticks/index.hbs
- website/partners/solutions/acr-analytics-llc/index.hbs
- website/partners/solutions/adept-marketing/index.hbs
- website/partners/solutions/ag-consult/index.hbs
- website/partners/solutions/american-eagle/index.hbs
- website/partners/solutions/analytics-pros/index.hbs
- website/partners/solutions/blast-analytics-and-marketing/index.hbs
- website/partners/solutions/blue-acorn/index.hbs
- website/partners/solutions/bluerank-sp-zoo/index.hbs
- website/partners/solutions/brooks-bell/index.hbs
- website/partners/solutions/bv-accel/index.hbs
- website/partners/solutions/catbirdseat/index.hbs
- website/partners/solutions/catchi/index.hbs
- website/partners/solutions/clearhead/index.hbs
- website/partners/solutions/conversion-factory/index.hbs
- website/partners/solutions/conversion-kings/index.hbs
- website/partners/solutions/conversion-rate-experts/index.hbs
- website/partners/solutions/conversionconsult/index.hbs
- website/partners/solutions/conversionista-ab/index.hbs
- website/partners/solutions/crometrics/index.hbs
The yml for partners had bad formatting. This PR fixes that. To test, compare staging with the current solutions partners: https://www.optimizely.com/partners/solutions/
Affected partners:
33-sticks
acr-analytics-llc
ag-consult
american-eagle
analytics-pros
blast-analytics-and-marketing
blue-acorn
bluerank-sp-zoo
brooks-bell
bv-accel
catbirdseat
catchi
clearhead
conversion-factory
conversion-kings
conversion-rate-experts
conversionconsult
conversionista-ab
crometrics
> fix yml for partners

- website/opticon/speakers/speakers_data.yml
> Opticon speaker edit

- website-guts/assets/css/pages/customers.scss
swap out sprites for new cutomer logos
> Update Customer Logos

- website/opticon/agenda/agenda_data.yml
- website/opticon/speakers/speakers_data.yml
update mary and spelling fixes
> Opticon Agenda & Speaker edits

- website/opticon/agenda/agenda_data.yml
> Opticon agenda updates

- website-guts/assets/js/pages/pricing.js
Console log left in for testing on staging, remove before pushing live
> Disable Get Started Now button after user clicks once

- website-guts/assets/js/pages/pricing.js
- website-guts/assets/js/utils/form_helpers/contact_sales.js
- website-guts/assets/js/utils/form_helpers/create_account_helpers.js
Redirect back to the mobile editor when referred from there.
https://optimizely.atlassian.net/browse/MKT-1946
> MKT-1946 -- Mobile redirect

- website/partners/solutions/freshegg-australia/index.hbs
Listing included UK info not Australia info.
> Update Fresh Egg Australia Listing

- website-guts/templates/components/modals/dev_signup_modal.hbs
@stewsmith this should be quick!
> switch dev signup endpoint

- website-guts/templates/layouts/wrapper.hbs
nav copy changes -- no hrefs yet
> Nav copy changes

- website/solutions/solutions.yml
Add p13n link to solutions page after blog launch.
> add p13n link

- website-guts/assets/css/layouts/opticon.scss
- website-guts/assets/css/pages/opticon-homepage.scss
- website-guts/templates/layouts/opticon.hbs
- website/opticon/global_opticon_data.yml
- website/opticon/index.hbs
- website/opticon/sponsors/index.hbs
@stewsmith This is a WIP PR, waiting for link to marketo lead capture page.
> update homepage for post-opticon

- Gruntfile.js
- grunt/s3.js
- package.json
Reverts optimizely/marketing-website#1190
> Revert "Cdee/update grunt aws plugin"

- website-guts/assets/css/pages/opticon-homepage.scss
@stewsmith Just needed to tweak the padding on the headline for the Opticon homepage
> tweaked padding in headline

- website-guts/assets/js/pages/partners-solutions.js
- website/partners/solutions/index.hbs
The js for partners/solutions was deleted so the dropdown isn't working anymore.
This PR adds the js back with a new file name.
> Add back partners solutions js

- website-guts/templates/partials/opticon_register.hbs
- website/opticon/index.hbs
Adds a "Get updates" section with a link to a Marketo landing page.
> Opticon 2016 Updates section

- website-guts/assets/js/pages/jobs.js
- website-guts/templates/layouts/about.hbs
This PR fixes the "Amsterdam, Paris" in the jobs location filter. It pulls from a separate offices greenhouse endpoint.
> Hit greenhouse api for office data

- website-guts/assets/js/utils/no-global/get-language-key.js
INTL-376 Fix create account flow so that new user account language preference matches the Marketing Site they were using
> do not use app-wide locales property to find locale

- website/faq/index.hbs
came in to fix the pageload question question link, found a bunch of other broken ones
> Update broken links in FAQ page

- website-guts/templates/components/modals/signin_modal.hbs
> Launch SSO on marketing site.

- website-guts/assets/js/layouts/trial-form.js
Reverts optimizely/marketing-website#1251
> Revert "Disable multiple form submissions on /free-trial"

- website-guts/assets/css/components/feature-list.scss
- website-guts/templates/partials/feature_list.hbs
- website/feature-list/global_feature_list.yml
- website/plans/index.hbs
- website/plans/pricing.yml
Reverts optimizely/marketing-website#1254
> Revert "Add more CTAs throughout plans page per test 2872490871"

- sitemap.xml
Updated all optimizely.jp URLs to optimizely.co.jp
> Update Japanese URLs to .co.jp

- website/ab-testing/index.hbs
Re-writing first paragraph to make it more Google Answer Box-friendly.
> Updating first paragraph

- website/feature-list/global_feature_list.yml
A bug was introduced to this table in March. This PR fixes formatting on the YAML so handlebars can render that table again
> Remove trailing dash in yaml to fix table and make it display

- website/opticon/sessions/sessions_data.yml
Round two of Opticon video uploads
> Add more videos to the page

- website/ab-testing/index.hbs
Removing extra header, optimizing for Google Answer Box
> Removing header

- website/ab-testing/index.hbs
Changing primary header from h4 to h2
> Updating header tag

- website/opticon/sessions/sessions_data.yml
Stew, as discussed, this is making our yaml more consistent by wrapping slides_url in quotes for each video
> Wrap slides URLs in quotes for consistency

- website-guts/templates/partials/faq_section.hbs
- website/plans/index.hbs
Adds back a `Contact Sales` button and `Contact Sales` bottom paragraph.
> Add back plans content

- website/index.hbs
https://optimizely.atlassian.net/browse/MKT-2196
> MKT-2196 -- change homepage headline copy

- website/opticon/sessions/sessions_data.yml
Our video production company finalized a few videos, which we have up now on the page.
> Add new videos to page

- test/pricing/pricing-spec.js
- website-guts/assets/js/pages/plans.js
run `grunt test`
I updated a few selectors to match the current page. I also moved the `Initial_Form_Source__c` and  `Inbound_Lead_Form_Type__c` out of a click handler.
@yesplease Can you review?
> Fix failing plans page tests

- grunt/jshint.js
- website-guts/assets/js/pages/opticon-sessions.js
- website/opticon/sessions/index.hbs
> Decoupled opticon sessions from hbs to js.

- website/case-studies/bleacher-report/index.hbs
- website/case-studies/hotwire/index.hbs
- website/case-studies/liftopia/index.hbs
- website/case-studies/secret-escapes/index.hbs
- website/case-studies/smarter-travel/index.hbs
- website/case-studies/smartwool/index.hbs
- website/case-studies/sony/index.hbs
- website/case-studies/spreadshirt/index.hbs
- website/case-studies/theclymb/index.hbs
- website/case-studies/upworthy/index.hbs
- website/case-studies/veggietales/index.hbs
> Scribe typo fixes

- website-guts/assets/js/pages/plans.js
Addressing this ticket:
https://optimizely.atlassian.net/browse/MKT-2160
please review @stewsmith @bhamodi
> Add functionality to open modals via url on /plans
